### ISSUE TITLE
Does not work without determining background in vimrc

### ISSUE THREAD

**Issue by Jorengarenar** [segeljakt/vim-stealth#1]
In my vimrc I have: `hi Normal ctermfg=DarkGreen` and I get that error:
```
Error detected while processing function stealth#toggle:                                                                                                                                                                               
line    6:
E421: Color name or number not recognized: ctermfg= guifg= ctermbg= guibg=
```
If I change that to this: `hi Normal ctermfg=DarkGreen ctermbg=black` plugin works, but still throws an error.

With that there is no error: `hi Normal ctermfg=DarkGreen ctermbg=black guibg=black `

To conclude: Plugin doesn't works with "default" background highlights.

**Comment by segeljakt** [comment]
Sorry about this and for the very belated response, it should hopefully be fixed in the latest commit.
