### ISSUE TITLE
Conceal instead of background color?

### ISSUE THREAD

**Issue by alter2000** [segeljakt/vim-stealth#2]
Maybe linking comments to the Conceal rule or something, IDK. Basically it's what vim uses in the help files (two hidden pipe chars surrounding terms) and some other plugins use for e.g printing actual lambdas in lambda expressions or hiding markup, etc.

**Comment by segeljakt** [comment]
Apologies for the late reply, I believe the latest commit should fix the background color bug. I linked the highlighting to the `Ignore` group which should have mostly the same effect. If anyone finds more bugs feel free to open a new issue.
